apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: s3onezone
type: Opaque
data:
  # Base64 encoded AWS credentials
  # Replace these with your actual base64 encoded credentials
  access-key-id: <base64-encoded-access-key-id>
  secret-access-key: <base64-encoded-secret-access-key>
  # Optional: session token for temporary credentials
  session-token: <base64-encoded-session-token>
