apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3express-app
  namespace: s3onezone
  labels:
    app: s3express-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3express-app
  template:
    metadata:
      labels:
        app: s3express-app
    spec:
      nodeSelector:
        eks.amazonaws.com/nodegroup: api-tool-pro
      serviceAccountName: s3express-sa
      containers:
      - name: s3express-container
        image: 123456789012.dkr.ecr.us-east-1.amazonaws.com/s3express-mountpoint:latest
        env:
        - name: AWS_REGION
          value: "us-east-1"
        - name: S3EXPRESS_BUCKET_NAME
          value: "one-zone-storage-demo--use1-az4--x-s3"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: secret-access-key
        securityContext:
          privileged: true  # Required for mounting
        resources:
          requests:
            memory: "1Gi"
            cpu: "50m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: s3express-service
  namespace: s3onezone
spec:
  selector:
    app: s3express-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP

